server:
  port: 7787

spring:
  application:
    name: fresh-user-service
    
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fresh?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: a
    
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
      
  session:
    store-type: redis
    
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 50000 
    jedis:
      pool:
        max-active: 8
        
  mail:
    host: smtp.qq.com # 邮件发送
    username: 1293580602@qq.com # 发送方的邮箱
    password: dihpepdwtahlgefh # 对于qq邮箱而言 密码指的就是发送方的授权码 
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml 
  type-aliases-package: com.yc.fresh.entity



server:
  tomcat:
    max-http-header-size: 8192
    uri-encoding: UTF-8  

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka

uploadload:
  photoPath: pics