# 服务器启动后占用的端口
server:
  port: 6868

eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: fresh-eureka-server # 自定义服务名称信息
    prfer-ip-address: true # 访问路径可以显示IP地址
  client:
    # 是否开启注册服务，因为这里如果为true表示自己注册自己，而自己就是一个服务注册方，没必要自己注册自己
    registerWithEureka: false
    # 是否拉取服务列表，这里我只提供服务给别的服务。
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    server:
      # 服务端开启自我保护模式。无论什么情况，服务端都会保持一定数量的服务。避免client与server的网络问题，而出现大量的服务被清除。
      enable-self-preservation: true
      # 开启清除无效服务的定时任务，时间间隔。默认1分钟
      evictionIntervalTimerInMs: 60000
      # 间隔多长时间，清除过期的delta数据
      deltaRetentionTimerIntervalInMs: 0
      # 过期数据，是否也提供给client
      disableDelta: false
      # 对于缓存的注册数据，多长时间过期
      responseCacheAutoExpirationInSeconds: 180
      # 多长时间更新一次缓存中的服务注册数据
      responseCacheUpdateIntervalMs: 3000
      #当时间戳不一致的时候，是否进行同步
      syncWhenTimestampDiffers: true 
      #是否采用只读缓存策略，只读策略对于缓存的数据不会过期。
      useReadOnlyResponseCache: true
  
      
      






